# Generated by Django 5.1.6 on 2025-02-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootdcastapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='warmth_level',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
