# Generated by Django 5.1.6 on 2025-02-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ootdcastapp', '0002_alter_clothingitem_warmth_level'),
    ]

    operations = [
    ]
